name: Run tests

on:
  push:
    branches:
    - main

    tags:
    - '*'

  pull_request:

jobs:
  test:
    strategy:
      matrix:
        php_ver: [ '8.1','8.0','7.4' ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      env:
        PHP_VER: ${{ matrix.php_ver }}
      run: make test
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: prepare artifact
      run: cp docker.mk Makefile && tar -czf docker4wordpress.tar.gz docker-compose.yml docker-compose.override.yml Makefile .env traefik.yml
    - name: get tag name
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - uses: xresloader/upload-to-github-release@v1
      id: upload_artifact
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: w6-wp-dev.tar.gz
        overwrite: true
        tags: true
        draft: false
        tag_name: ${{ steps.vars.outputs.tag }}
